### ISSUE TITLE
Weird crash for weird domain

### ISSUE THREAD

**Issue by kecso** [VUISIS/formula-dotnet#21]
Here is the 4ml content:

```
domain AlgTrees
{
    Node ::= new (left: any Node + {NIL}, right: any Node + {NIL}).
    Root ::= new (root: any Node).

    height ::= (Node, Integer).
    height(x,c) :- x.left = NIL, x.right = NIL, c = 0.
    height(x,c) :- x.left = NIL, x.right != NIL, height(x.right,d), c = d+1.
    height(x,c) :- x.right = NIL, x.left != NIL, height(x.left,d), c = d+1.
    height(x,c) :- x.left != NIL, x.right != NIL, height(x.left,d), height(x.right,e), d >= e, c = d+1.
    height(x,c) :- x.left != NIL, x.right != NIL, height(x.left,d), height(x.right,e), d < e, c = e+1.

}

model LessThanTwoLevels of AlgTrees
{
    node1 is Node(NIL,NIL).  
    node2 is Node(node1, NIL).
    node3 is Node(node2, NIL).
    Root(node3).
}
```
for some reason, even the simplest query `qr LessThanTwoLevels r is Root` will cause the following crash:
```
[]> Process terminated. Assertion failed.
   at Microsoft.Formula.Common.Rules.CoreRule.Execute(Term binding, Int32 findNumber, Executer index, Boolean keepDerivations, Map`2 pending) in C:\WORK\formula-dotnet\Src\Core\Common\Rules\CoreRule.cs:line 919
   at Microsoft.Formula.Common.Rules.Executer.Execute() in C:\WORK\formula-dotnet\Src\Core\Common\Rules\Executer.cs:line 253
   at Microsoft.Formula.API.QueryResult.Start() in C:\WORK\formula-dotnet\Src\Core\API\Results\QueryResult.cs:line 99
   at Microsoft.Formula.API.Env.<>c__DisplayClass33_0.<Query>b__0() in C:\WORK\formula-dotnet\Src\Core\API\Base\Env.cs:line 955
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s)
   at System.Threading.Thread.StartCallback()
```

**Comment by balasub** [comment]
Initial investigation reveals that the correct internal representation is not being generated for some rules. For example, with this rule:

height(x,c) :- x.left = NIL, x.right != NIL, height(x.right,a), c = a + 1.

The internal representation is not correct because it does not "implicitly" generate a variable x that is a Node. This should probably be flagged as an error in the compilation phase.

A workaround is to write your domain in the following way:

domain AlgTrees2
{
    Node ::= new (left: any Node + {NIL}, right: any Node + {NIL}).
    Root ::= new (root: any Node).

    height ::= (Node, Integer).
	
    height(x,c) :- x is Node, x.left = NIL, x.right = NIL, c = 0. // explicitly declare x as a Node in each rule
    height(x,c) :- x is Node, x.left = NIL, x.right != NIL, height(x.right, a), c = a + 1.
    height(x,c) :- x is Node, x.right = NIL, x.left != NIL, height(x.left, b), c = b + 1.
    height(x,c) :- x is Node, x.left != NIL, x.right != NIL, height(x.left, q), height(x.right, e), q >= e, c = q + 1.
    height(x,c) :- x is Node, x.left != NIL, x.right != NIL, height(x.left, z), height(x.right, e), z < e, c = e + 1.
}

model m2 of AlgTrees2
{
    node1 is Node(NIL, NIL).  
    node2 is Node(node1, NIL).
    node3 is Node(node2, NIL).
    Root(node3).
}

**Comment by balasub** [comment]
We should probably address this issue in two ways:

1. Create a linting rule with tree-sitter to warn users.
2. Reject it during the loading phase.

@saj122 Can you take a look at a tree-sitter rule to catch this?

**Comment by saj122** [comment]
I added a folder for linters with a sub category for rules. This will catch the error at compile time. A query for the same rule can be written for tree sitter. This will now fail to load when trying without binding the variable to a type. Example of the error message when loading the broken 4ml versus when fixed:

<img width="1027" alt="rule-linting" src="https://user-images.githubusercontent.com/8409466/184546062-8e06b2cd-ad4e-4741-805f-f279e36990b0.png">

Repo is on branch rule-linting and pull request here:

https://github.com/VUISIS/formula-dotnet/pull/33
.

**Comment by balasub** [comment]
Thanks, looks good. Closing this issue.
